import Head from "next/head";

import Header from "./Header";
import Footer from "./Footer";
import ArtistHeader from "./ArtistHeader";
import HeaderHidden from "./HeaderHidden";

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>New Space</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full h-full flex flex-col justify-between">
        <div className="flex flex-col">
          <Header />
          <ArtistHeader />
        </div>

        {children}

        <div className="flex flex-col">
          <HeaderHidden />
          <Footer />
        </div>
      </div>
    </>
  );
};
export default Layout;
