import Face from "@/components/FaceHome";
import { Container } from "@mui/material";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Geru</title>
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Manrope:wght@700&display=swap');
        </style>
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=PT+Sans+Narrow:wght@700&display=swap');
        </style>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Container>
        <Face />
      </Container>
    </>
  );
}
