import Cart from "@/components/Cart";
import Head from "next/head";
import Face from "./HomeDefault";
import ArtistDetail from "./ArtistDetail";
import CollectionArtist from "@/components/CollectionArtist";
import Basket from "@/components/Basket";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Basket />
    </>
  );
}
